"""
src/integrations/reporter.py - GitHub PR comment generator.

Formats triage assessments into structured markdown comments containing
SVG status badges, calibrated risk percentages, collapsible SHAP feature
attributions, and actionable recommendations for code reviewers.
"""
from typing import Optional, Union
from src.api.schemas import TriageResponse


# Status badges per risk tier
BADGE_URLS = {
    "LOW": "https://img.shields.io/badge/ASTRA_Risk-LOW_Fast_Track-28a745.svg",
    "MEDIUM": "https://img.shields.io/badge/ASTRA_Risk-MEDIUM_Standard_Review-e3a21a.svg",
    "HIGH": "https://img.shields.io/badge/ASTRA_Risk-HIGH_Deprioritize-dc3545.svg",
}

TIER_EMOJIS = {
    "LOW": "🟢",
    "MEDIUM": "🟡",
    "HIGH": "🔴",
}


def generate_markdown_report(
    triage: TriageResponse,
    repo_name: Optional[str] = None,
    pr_number: Optional[int] = None,
) -> str:
    """
    Constructs an informative GitHub PR markdown comment from a TriageResponse.

    Args:
        triage: TriageResponse schema instance containing model results.
        repo_name: Optional repository name for context.
        pr_number: Optional pull request number.

    Returns:
        Formatted GitHub markdown comment string.
    """
    tier = (triage.risk_tier or "MEDIUM").upper()
    badge_url = BADGE_URLS.get(tier, BADGE_URLS["MEDIUM"])
    emoji = TIER_EMOJIS.get(tier, "⚪")

    risk_percent = round(triage.risk_probability * 100.0, 1)
    target_pr = pr_number or triage.pr_number
    pr_label = f"PR #{target_pr}" if target_pr else "PR"
    if repo_name:
        pr_label = f"{repo_name} #{target_pr}"

    lines = [
        "## ASTRA Automated Triage Report",
        "",
        f"[![Risk Tier]({badge_url})](#)",
        "",
        f"**Risk Evaluation for {pr_label}:** {emoji} **{tier} RISK** ({risk_percent}% defect probability)",
        "",
        f"> **Recommendation:** {triage.recommendation}",
    ]

    if triage.override_applied:
        lines.extend([
            "",
            "> [!WARNING]",
            f"> **Safety Override Active:** {triage.override_applied}",
        ])

    lines.extend([
        "",
        "### Review Assessment Summary",
        "",
        f"- **Calibrated Defect Probability:** `{triage.risk_probability:.4f}` ({risk_percent}%)",
        f"- **Risk Classification Tier:** `{tier}`",
        f"- **Analysis Latency:** `{triage.latency_ms:.1f} ms`",
    ])

    if triage.raw_risk_score is not None:
        lines.append(f"- **Raw Decision Score:** `{triage.raw_risk_score:.4f}`")

    # Collapsible SHAP Feature Attribution Details
    lines.extend([
        "",
        "<details>",
        "<summary><b>Top Structural and Semantic Risk Drivers (SHAP Attribution)</b></summary>",
        "",
        "| Rank | Feature | Impact | Marginal SHAP | Details |",
        "| :--- | :--- | :--- | :--- | :--- |",
    ])

    if triage.top_risk_drivers:
        for idx, item in enumerate(triage.top_risk_drivers, start=1):
            impact_display = item.impact or ("Increases Risk" if item.shap_value > 0 else "Decreases Risk")
            sign = "+" if item.shap_value > 0 else ""
            shap_formatted = f"`{sign}{item.shap_value:.4f}`"
            lines.append(
                f"| {idx} | `{item.feature_name}` | {impact_display} | {shap_formatted} | {item.description} |"
            )
    else:
        lines.append("| - | No significant risk drivers identified | Neutral | `0.0000` | Baseline nominal changes |")

    lines.extend([
        "",
        "</details>",
        "",
        "---",
        "*Automated risk stratification generated by [ASTRA](https://github.com/ameya2401/ASTRA). "
        "Intended for triage guidance and review prioritization, not autonomous merging.*",
    ])

    return "\n".join(lines)
